### ISSUE TITLE
Process notification services even if the GitHub API is giving an error

### ISSUE THREAD

**Issue by timbru31** [upptime/upptime#186]
**Describe the bug**

This is actually a bug report that affect multiple issues all related to the root cause below:
- upptime does not retry to create the issue for the service which is down
- The code execution seems to stop, other services (Discord, Telegram, ...) are not notified
- The used API query might not be ideal

In my case the GitHub API throws sometimes an error (502) when listing my open issues:
```
ERROR RequestError [HttpError]: Server Error
    at /home/runner/work/_actions/upptime/uptime-monitor/v1.24.2/node_modules/@octokit/request/dist-node/index.js:66:1
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.update (/home/runner/work/_actions/upptime/uptime-monitor/v1.24.2/dist/update.js:140:1) {
  name: 'HttpError',
  status: 502,
  headers: {
    connection: 'close',
    'content-length': '32',
    'content-type': 'application/json',
    date: 'Thu, 07 Jan 2021 19:47:20 GMT',
    etag: '"5ff75d5a-20"',
    server: 'GitHub.com',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-github-request-id': '07C2:4F50:2368537:641941E:5FF7653E'
  },
  request: {
    method: 'GET',
    url: 'api.github.com/issues?owner=Dustplanet&repo=upptime&labels=jenkins&filter=all&state=open&sort=created&direction=desc&per_page=1',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'KojBot octokit-rest.js/17.11.2 octokit-core.js/2.5.4 Node.js/12.13.1 (Linux 5.4; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  }
}
```
(See run https://github.com/Dustplanet/upptime/runs/1664693513?check_suite_focus=true)

I assume this might be because of the amount of issues the API needs to filter before returning the result.
When I remove some filters I see all the issues that are, e.g., in the Apache organization (i.e., A LOT), because I'm a member of this org.
**Maybe the API call can be optimized, too?**

However, the workflow run continued to run 👍 
Sadly, my other notification triggers such as Webhook and Telegram were not triggered because the API call above failed.

**To Reproduce**
1. Have a GH account with many issues returned by the API
2. CI check runs and fails
3. Notifications are not sent, issue is not opened.
4. See error above

**Expected behavior**

It would be better if the other notification services are notified and do not fail silentnly when GitHub's API is slow/down/unavailable.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by timbru31** [comment]
For the API call, maybe https://docs.github.com/en/free-pro-team@latest/rest/reference/issues#list-repository-issues is better suited than the big list of "List issues assigned to the authenticated user"
