### ISSUE TITLE
History always shows "7-day response time" chart and never 30d or 1y

### ISSUE THREAD

**Issue by thomasmerz** [upptime/upptime#264]
When clicking on the "Live status" page on any monitored service there's always the "7-day response time" chart shown and never "30d" or "1y" 😞

For example:
<img width="762" alt="image" src="https://user-images.githubusercontent.com/18568381/108366544-ca03b200-71f8-11eb-9dc5-93b9980cce7e.png">
Click on the "30d" chart leads to https://demo.upptime.js.org/history/google which only shows the 7d chart.

🙏🏻 Please provide the possibility to show/click other charts (30d, 1y), too.

**Comment by thomasmerz** [comment]
This is also valid for `README.md`

**Comment by Nirmitjatana** [comment]
interesting addition

**Comment by ArchitBhonsle** [comment]
I could try adding this but just forking and cloning the repo and running `npm run dev` doesn't seem to work and I get this:
```
❯ npm run dev

> @upptime/status-page@1.12.4 dev /home/puipuituipui/Github/status-page
> npm run pre-process && sapper dev


> @upptime/status-page@1.12.4 pre-process /home/puipuituipui/Github/status-page
> ts-node pre-process.ts

(node:5710) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '../.upptimerc.yml'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5710) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5710) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✗ server
Could not resolve '../data/config.json' from src/routes/_layout.svelte
✗ client
Could not resolve '../data/config.json' from src/routes/_layout.svelte
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '/home/puipuituipui/Github/status-page/__sapper__/dev/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
> Server crashed
• service worker
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
No directory provided. Skipping CSS generation
```

So what's the best way to get started with this?

**Comment by ArchitBhonsle** [comment]
I'll try adding this. So will a selector like this:
![image](https://user-images.githubusercontent.com/34616931/121689169-ef873500-cae1-11eb-9bd6-dca7e05ff78d.png)
above the graphs do?

**Comment by thomasmerz** [comment]
@ArchitBhonsle , when clicking on the "dates" (24h, 7d, …) the graph on the status-page is showing the right graph for this selected time-range - but when clicking on the graph, you will always only get the "7-day response time" - not what you have selected before! 😞

**Comment by ArchitBhonsle** [comment]
Yeah, so I was planning to add a similar selector on the history page as well. However, I see the limitation now, it's fetching all the recent commits with octokit and plotting them. I guess this gets slow for bigger numbers.

The ideal way to do this would be to maintain this I guess would be maintaining a file of these responses. I'm quite new to this so I'm not entirely sure how this would work.

**Comment by thomasmerz** [comment]
There's no need to plot them **again** - the graphs are already there. Have a look:

https://github.com/thomasmerz/upptime/tree/master/graphs/nextcloud
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/18568381/121704569-2a826c00-cad4-11eb-9c56-cbc8b5216524.png">


🕵🏻‍♂️  In detail:

<img width="972" alt="image" src="https://user-images.githubusercontent.com/18568381/121704742-5140a280-cad4-11eb-928c-c1caafb384ae.png">

Which should show [this](https://github.com/thomasmerz/upptime/blob/master/graphs/nextcloud/response-time-month.png) when 30d is selected and graph is clicked.

**Comment by ArchitBhonsle** [comment]
I think the difference between the two is that the ones displayed on the main page are just images while in the individual history pages they are plotted using chartjs.

**Comment by ArchitBhonsle** [comment]
I think I figured out a way to do this properly. The graphs (pngs on the home page) in the repo are generated using the [graphs](https://github.com/upptime/graphs) module. However, when you visit the website specific page it uses octokit to query for the commits.

So @AnandChowdhary I think the better way to do this would be saving a json with all the response times alongside the png since the [graphs](https://github.com/upptime/graphs) module does this anyway which will serve as a pseudo-api for the [status page](https://github.com/upptime/status-page). This would allow us to show charts on par with the ones on the home page but these would also be interactive since they'd be rendered using a graphing library.

My only apprehension against this would be separation of concerns I guess? The graphing module creating the "api" seems kinda weird but sorta makes sense since it's graphing information?

**Comment by thomasmerz** [comment]
@ArchitBhonsle - Are you stuck on this? Can anyone help or do something to get this done? I'm no developer, "just" linux admin using this great upptime-repo… 🤷🏻‍♂️
