### ISSUE TITLE
Notification Telegram not works

### ISSUE THREAD

**Issue by Rmunuera** [upptime/upptime#487]
I configured the notification in order send messages, when de status pages changed the notifications didnt send.

The log´s show me this :

```
Sending Telegram
Got an error Error: Request failed with status code 400
at createError (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/node_modules/axios/lib/core/createError.js:16:1)
at settle (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/node_modules/axios/lib/core/settle.js:17:1)
at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/node_modules/axios/lib/adapters/http.js:260:1)
at IncomingMessage.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1184:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21) {
config: {
url: 'https://api.telegram.org/bot***/sendMessage',
method: 'post',
data: '{"parse_mode":"Markdown","disable_web_page_preview":***,"chat_id":"***","text":"🟩 mysite (https://www.***mysite.com.br) is back up."}',
headers: {
Accept: 'application/json, text/plain, */*',
'Content-Type': 'application/json;charset=utf-8',
'User-Agent': 'axios/0.21.1',
'Content-Length': 169
},
transformRequest: [ [Function: transformRequest] ],
transformResponse: [ [Function: transformResponse] ],
timeout: 0,
adapter: [Function: httpAdapter],
xsrfCookieName: 'XSRF-TOKEN',
xsrfHeaderName: 'X-XSRF-TOKEN',
maxContentLength: -1,
maxBodyLength: -1,
validateStatus: [Function: validateStatus]
},
```

**Comment by jayantkatia** [comment]
Hey @Rmunuera,  getting ```400``` status code might suggest that your ```bot_token``` or ```chat_id``` might be incorrect. I suggest you to recheck it.

I tried using telegram notifications and it works fine.

Use 
```
https://api.telegram.org/bot{token}/sendMessage?chat_id=<chat_id>&text=<Enter your text here>
```
to test your token and chat_id.

**Comment by Rmunuera** [comment]
Hello @jayantkatia,

I reconfigure the secrets in order do tests with this values:

NOTIFICATION_TELEGRAM: true
NOTIFICATION_TELEGRAM_BOT_KEY: token get from botfather
NOTIFICATION_TELEGRAM_CHAT_ID: I used my id and the a id group 

But it didn't work.
Using the telegram api link, with the same bot_key and the chat_id and the messages arrive normally for me.

I tried use the Postman with the chat_id and bot_key and its works too.

**Comment by Rmunuera** [comment]
Hello @jayantkatia 

I found where the problem occours.

When I use a url with the filename example:

https://www.mysite.com/teste_1.php the problem happens, telegram dont send message and return error code 400

but If I use this url https://www.mysite.com/ the telegram send notification normally

I use the filename to run some internal tests before responding, rather than verifying that only the site is up and running.

**Comment by jayantkatia** [comment]
:wave: Hello @Rmunuera, 
I copied the [axios request from the upptime-monitor](https://github.com/upptime/uptime-monitor/blob/master/src/helpers/notifme.ts#L232) and ran it locally(using the same axios version).

:thinking: Strange !! 
The code and ```axios v0.21.1``` works fine on testing. Are we missing out on the error from the logs? :thinking:

**Comment by Rmunuera** [comment]
@jayantkatia 

The problem is because in the url exists the underline, the code need escape this before send message. 

Example if the message is "Hello it is a test" works fine. But if the message is "Hello it is a test_" the problem occurs. 

If the message send this way "Hello it is a teste \_" it is send normally.
