### ISSUE TITLE
<website> is down, even if it's not

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [upptime/upptime#495]
i forked the repo and followed instructions at https://upptime.js.org/docs/get-started/ and after everything is done the bot is telling me all of my websites are down even tho i checked all of them and all are working fine so what causes it?
here is my repo feel free to check it's config: https://github.com/EsmailELBoBDev2/status-page

**Comment by dismantl** [comment]
I am also getting a lot of false positives (i.e. alerts about downtime when the website is still up) lately with Upptime. Are there any settings to tweak around how the checks are done that could lead to less false positives?

**Comment by ajhalili2006** [comment]
In my case, since most of the domains I monitor are from Freenom, I found an reference error and mostly request timeouts on my CI logs. Source logs are at <https://github.com/RecapTime/status-page/runs/4866080329?check_suite_focus=true>.

```
Found ongoing ***tenance events 0
Checking https://recaptime.tk
Current status undefined up 2021-12-22T09:25:01.000Z
Using tcp-ping instead of curl
Got pinging error ReferenceError: Cannot access 'responseTime' before initialization
    at performTestOnce (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/dist/update.js:105:1)
    at Object.update (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/dist/update.js:171:45)
Using tcp-ping instead of curl
Got result {
  address: 'https://recaptime.tk',
  port: 80,
  attempts: 5,
  avg: NaN,
  max: undefined,
  min: undefined,
  results: [
    {
      seq: 0,
      time: undefined,
      err: Error: Request timeout
          at Socket.<anonymous> (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/node_modules/tcp-ping/ping.js:77:27)
          at Object.onceWrapper (events.js:299:28)
          at Socket.emit (events.js:210:5)
          at Socket._onTimeout (net.js:469:8)
          at listOnTimeout (internal/timers.js:531:17)
          at processTimers (internal/timers.js:475:7)
    },
    {
      seq: 1,
      time: undefined,
      err: Error: Request timeout
          at Socket.<anonymous> (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/node_modules/tcp-ping/ping.js:77:27)
          at Object.onceWrapper (events.js:299:28)
          at Socket.emit (events.js:210:5)
          at Socket._onTimeout (net.js:469:8)
          at listOnTimeout (internal/timers.js:531:17)
          at processTimers (internal/timers.js:475:7)
    },
    {
      seq: 2,
      time: undefined,
      err: Error: Request timeout
          at Socket.<anonymous> (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/node_modules/tcp-ping/ping.js:77:27)
          at Object.onceWrapper (events.js:299:28)
          at Socket.emit (events.js:210:5)
          at Socket._onTimeout (net.js:469:8)
          at listOnTimeout (internal/timers.js:531:17)
          at processTimers (internal/timers.js:475:7)
    },
    {
      seq: 3,
      time: undefined,
      err: Error: Request timeout
          at Socket.<anonymous> (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/node_modules/tcp-ping/ping.js:77:27)
          at Object.onceWrapper (events.js:299:28)
          at Socket.emit (events.js:210:5)
          at Socket._onTimeout (net.js:469:8)
          at listOnTimeout (internal/timers.js:531:17)
          at processTimers (internal/timers.js:475:7)
    },
    {
      seq: 4,
      time: undefined,
      err: Error: Request timeout
          at Socket.<anonymous> (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/node_modules/tcp-ping/ping.js:77:27)
          at Object.onceWrapper (events.js:299:28)
          at Socket.emit (events.js:210:5)
          at Socket._onTimeout (net.js:469:8)
          at listOnTimeout (internal/timers.js:531:17)
          at processTimers (internal/timers.js:475:7)
    }
  ]
}
Skipping commit,  status is up
Checking https://bw.rtapp.tk/alive
Current status undefined down 2021-12-22T09:25:10.000Z
Got an error (on error) [Error: Timeout was reached]
Result from test 0 0
Got an error (on error) [Error: Timeout was reached]
Result from test 0 0
Got an error (on error) [Error: Timeout was reached]
Result from test 0 0
Skipping commit,  status is down
Checking https://go.rtapp.tk/ping
Current status undefined down 2021-12-22T09:25:17.000Z
Got an error (on error) [Error: Timeout was reached]
Result from test 0 0
Got an error (on error) [Error: Timeout was reached]
Result from test 0 0
Got an error (on error) [Error: Timeout was reached]
Result from test 0 0
Skipping commit,  status is down
Checking https://rtapp.tk
Current status undefined down 2021-12-22T09:25:22.000Z
Got an error (on error) [Error: Timeout was reached]
Result from test 0 0
Got an error (on error) [Error: Timeout was reached]
Result from test 0 0
Got an error (on error) [Error: Timeout was reached]
Result from test 0 0
Skipping commit,  status is down
Checking https://wiki.rtapp.tk
Current status undefined up 2022-01-19T09:00:50.000Z
Using tcp-ping instead of curl
Got pinging error ReferenceError: Cannot access 'responseTime' before initialization
    at performTestOnce (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/dist/update.js:105:1)
    at Object.update (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/dist/update.js:171:45)
Using tcp-ping instead of curl
Got result {
  address: 'https://wiki.rtapp.tk',
  port: 80,
  attempts: 5,
  avg: NaN,
  max: undefined,
  min: undefined,
  results: [
    {
      seq: 0,
      time: undefined,
      err: Error: Request timeout
          at Socket.<anonymous> (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/node_modules/tcp-ping/ping.js:77:27)
          at Object.onceWrapper (events.js:299:28)
          at Socket.emit (events.js:210:5)
          at Socket._onTimeout (net.js:469:8)
          at listOnTimeout (internal/timers.js:531:17)
          at processTimers (internal/timers.js:475:7)
    },
    {
      seq: 1,
      time: undefined,
      err: Error: Request timeout
          at Socket.<anonymous> (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/node_modules/tcp-ping/ping.js:77:27)
          at Object.onceWrapper (events.js:299:28)
          at Socket.emit (events.js:210:5)
          at Socket._onTimeout (net.js:469:8)
          at listOnTimeout (internal/timers.js:531:17)
          at processTimers (internal/timers.js:475:7)
    },
    {
      seq: 2,
      time: undefined,
      err: Error: Request timeout
          at Socket.<anonymous> (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/node_modules/tcp-ping/ping.js:77:27)
          at Object.onceWrapper (events.js:299:28)
          at Socket.emit (events.js:210:5)
          at Socket._onTimeout (net.js:469:8)
          at listOnTimeout (internal/timers.js:531:17)
          at processTimers (internal/timers.js:475:7)
    },
    {
      seq: 3,
      time: undefined,
      err: Error: Request timeout
          at Socket.<anonymous> (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/node_modules/tcp-ping/ping.js:77:27)
          at Object.onceWrapper (events.js:299:28)
          at Socket.emit (events.js:210:5)
          at Socket._onTimeout (net.js:469:8)
          at listOnTimeout (internal/timers.js:531:17)
          at processTimers (internal/timers.js:475:7)
    },
    {
      seq: 4,
      time: undefined,
      err: Error: Request timeout
          at Socket.<anonymous> (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/node_modules/tcp-ping/ping.js:77:27)
          at Object.onceWrapper (events.js:299:28)
          at Socket.emit (events.js:210:5)
          at Socket._onTimeout (net.js:469:8)
          at listOnTimeout (internal/timers.js:531:17)
          at processTimers (internal/timers.js:475:7)
    }
  ]
}
Skipping commit,  status is up
Everything up-to-date
```

**Comment by EsmailELBoBDev2** [comment]
if i can read wirte (probably not) it's timeout errors so maybe bot can't really access sites or it's blocked?

if github actions uses it's github ips maybe some of their ips are blocked and it report timeout (or refused)

**Comment by matgott** [comment]
any update on this? I have an online website but Upptime trigger a downtime alert

**Comment by EsmailELBoBDev2** [comment]
It actually works for me (*out of no where*) after some time i gave it a try again and it just works so i really do not know

**Comment by dismantl** [comment]
I am now getting false positive downtime alerts dozens of times a day, I am about to give up on Upptime at this point. Is there anything that can be done about this?

**Comment by EsmailELBoBDev2** [comment]
I get it too, I think its because of github actions

**Comment by ooliver1** [comment]
i have a "complete outage" and it shows response times for all of them, they are not down and the uptime ci says that too but committing insists its down even when i edit the database

**Comment by dontkillsheep225** [comment]
Im trying to debug this

**Comment by jrpedrianes** [comment]
The same thing is happening to us. For a few weeks now, up until today (we’ve had Uptime installed for about 7 months), Uptime has started reporting false positives. We set up the same configuration using another paid tool (but only utilising the free tier it offers), and we aren’t receiving alerts from that application, only from Uptime.
