### ISSUE TITLE
"tcp-ping" produces 0ms ping

### ISSUE THREAD

**Issue by ooliver1** [upptime/upptime#533]
**Describe the bug**

i have set up a tcp-ping checked url (ip.ip.ip.ip:port) and it produces 0ms ping

**To Reproduce**
1. Edit configuration to a valid ip:port tcp server
2. Commit
3. Wait
4. See error in actions, see 0ms ping in readme and status page

**Expected behavior**
More accurate ping timing 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 
### __**the two above are incredibly unrelated to upptime at all**__

**Additional context**

```js
Using tcp-ping instead of curl
[29](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:29)
Got pinging error ReferenceError: Cannot access 'responseTime' before initialization
[30](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:30)
    at performTestOnce (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/dist/update.js:105:1)
[31](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:31)
    at Object.update (/home/runner/work/_actions/upptime/uptime-monitor/v1.26.4/dist/update.js:171:45)
[32](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:32)
Using tcp-ping instead of curl
[33](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:33)
Got result {
[34](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:34)
  address: '***',
[35](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:35)
  port: 80,
[36](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:36)
  attempts: 5,
[37](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:37)
  avg: NaN,
[38](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:38)
  max: undefined,
[39](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:39)
  min: undefined,
[40](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:40)
  results: [
[41](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:41)
Error: eq: 0, time: undefined, err: [Error] },
[42](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:42)
Error: eq: 1, time: undefined, err: [Error] },
[43](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:43)
Error: eq: 2, time: undefined, err: [Error] },
[44](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:44)
Error: eq: 3, time: undefined, err: [Error] },
[45](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:45)
Error: eq: 4, time: undefined, err: [Error] }
[46](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:46)
  ]
[47](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:47)
}
[48](https://github.com/ooliver1/status/runs/5518075524?check_suite_focus=true#step:3:48)
[master 2c6a5e0] 🟩 Minecat WS is up (200 in 0 ms) [skip ci] [upptime]
```

**Comment by ooliver1** [comment]
I also do not use port 80, so no idea how it is showing up port 80

**Comment by ooliver1** [comment]
https://github.com/upptime/uptime-monitor/blob/master/src/update.ts#L115-L135 if an error is caught, the response time is undefined

**Comment by ooliver1** [comment]
the undocumented ws check (actually uptiming a websocket) will always produce a 0ms response time too https://github.com/upptime/uptime-monitor/blob/master/src/update.ts#L140

**Comment by ooliver1** [comment]
seems as though the incredibly undocumented tcp-ping required a proper port to work
