### ISSUE TITLE
Typescript error on Generate Site

### ISSUE THREAD

**Issue by KaspianDev** [upptime/upptime#578]
**Describe the bug**
I tried to run upptime with almost default setup but it fails generating the site.

**Logs**
https://www.toptal.com/developers/hastebin/xoduyuweti.typescript

**Comment by Cyb3r-Jak3** [comment]
Same here: https://github.com/Cyb3r-Jak3/uptime-stats/runs/6583704392?check_suite_focus=true

**Comment by qwerzl** [comment]
Same here

**Comment by AnandChowdhary** [comment]
Me too on the official upptime/upptime repo: https://github.com/upptime/upptime/runs/6585123364?check_suite_focus=true

**Comment by mariojmdavid** [comment]
"yet another same here" https://github.com/gbifatlas/status/runs/6587519856?check_suite_focus=true#step:3:96

**Comment by KaspianDev** [comment]
Wow i thought it was my dumb mistake

Is that something with the upptime itself or rather github?
@AnandChowdhary

**Comment by faithfulojebiyi** [comment]
same issue

**Comment by rouilj** [comment]
ditto: https://github.com/rouilj/RoundupAssets/actions/runs/2388379300

**Comment by thomasmerz** [comment]
Me, too… 🤷🏻‍♂️

**Comment by KaKi87** [comment]
Please stop, this is unnecessary. Just click *thumbs up* and *subscribe*, then go.

**Comment by modem7** [comment]
Posting to update regarding the latest release. 

Unfortunately the latest (1.12.5) release also has the issue. 

@upptime-bot 

```
Error: exec: 
/home/runner/work/Status/Status/site/node_modules/typescript/lib/typescript.js:42530
        ts.Debug.assert(typeof typeReferenceDirectiveName === "string", "Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.");
                 ^
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (/home/runner/work/Status/Status/site/node_modules/typescript/lib/typescript.js:42530:18)
    at /home/runner/work/Status/Status/site/node_modules/ts-node/src/index.ts:623:55
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/home/runner/work/Status/Status/site/node_modules/ts-node/src/index.ts:622:33)
    at actualResolveTypeReferenceDirectiveNamesWorker (/home/runner/work/Status/Status/site/node_modules/typescript/lib/typescript.js:116611:163)
    at resolveTypeReferenceDirectiveNamesWorker (/home/runner/work/Status/Status/site/node_modules/typescript/lib/typescript.js:116911:26)
    at processTypeReferenceDirectives (/home/runner/work/Status/Status/site/node_modules/typescript/lib/typescript.js:118393:31)
    at findSourceFileWorker (/home/runner/work/Status/Status/site/node_modules/typescript/lib/typescript.js:1182[78](https://github.com/modem7/Status/runs/6609669083?check_suite_focus=true#step:3:79):21)
    at findSourceFile (/home/runner/work/Status/Status/site/node_modules/typescript/lib/typescript.js:11[81](https://github.com/modem7/Status/runs/6609669083?check_suite_focus=true#step:3:82)33:26)
    at processImportedModules (/home/runner/work/Status/Status/site/node_modules/typescript/lib/typescript.js:118539:25)

        ts.Debug.assert(typeof typeReferenceDirectiveName === "string", "Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.");
                 ^
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (/home/runner/work/Status/Status/site/node_modules/typescript/lib/typescript.js:42530:18)
    at /home/runner/work/Status/Status/site/node_modules/ts-node/src/index.ts:623:55
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/home/runner/work/Status/Status/site/node_modules/ts-node/src/index.ts:622:33)
    at actualResolveTypeReferenceDirectiveNamesWorker (/home/runner/work/Status/Status/site/node_modules/typescript/lib/typescript.js:116611:163)
    at resolveTypeReferenceDirectiveNamesWorker (/home/runner/work/Status/Status/site/node_modules/typescript/lib/typescript.js:116911:26)
    at processTypeReferenceDirectives (/home/runner/work/Status/Status/site/node_modules/typescript/lib/typescript.js:118393:31)
    at findSourceFileWorker (/home/runner/work/Status/Status/site/node_modules/typescript/lib/typescript.js:11[82](https://github.com/modem7/Status/runs/6609669083?check_suite_focus=true#step:3:83)78:21)
    at findSourceFile (/home/runner/work/Status/Status/site/node_modules/typescript/lib/typescript.js:118133:26)
    at processImportedModules (/home/runner/work/Status/Status/site/node_modules/typescript/lib/typescript.js:11[85](https://github.com/modem7/Status/runs/6609669083?check_suite_focus=true#step:3:86)39:25)

    at Object.error (/home/runner/work/_actions/upptime/uptime-monitor/v1.27.0/node_modules/shelljs/src/common.js:110:1)
    at execSync (/home/runner/work/_actions/upptime/uptime-monitor/v1.27.0/dist/index.js:1511[91](https://github.com/modem7/Status/runs/6609669083?check_suite_focus=true#step:3:92):12)
    at Object._exec (/home/runner/work/_actions/upptime/uptime-monitor/v1.27.0/dist/index.js:1512[94](https://github.com/modem7/Status/runs/6609669083?check_suite_focus=true#step:3:95):12)
    at Object.exec (/home/runner/work/_actions/upptime/uptime-monitor/v1.27.0/node_modules/shelljs/src/common.js:335:1)
    at Object.generateSite (/home/runner/work/_actions/upptime/uptime-monitor/v1.27.0/dist/site.js:40:1)
    at processTicksAndRejections (internal/process/task_queues.js:[97](https://github.com/modem7/Status/runs/6609669083?check_suite_focus=true#step:3:98):5)
```

**Comment by AnandChowdhary** [comment]
This is fixed now in https://github.com/upptime/status-page/releases/tag/v1.12.6. You don't to update anything, it should just work if you manually run "Static Site CI", or it'll auto-run tomorrow and it should all be green again.

I'll keep this issue open until one of you confirms that it's working for you.

Cheers!

**Comment by modem7** [comment]
> This is fixed now in https://github.com/upptime/status-page/releases/tag/v1.12.6. You don't to update anything, it should just work if you manually run "Static Site CI", or it'll auto-run tomorrow and it should all be green again.
> 
> I'll keep this issue open until one of you confirms that it's working for you.
> 
> Cheers!

Confirmed working. 

Thank you for your efforts!

**Comment by KaspianDev** [comment]
Can confirm, closing.
