### ISSUE TITLE
Error when Build

### ISSUE THREAD

**Issue by Intelecta** [upptime/upptime#694]
Suddenly, i have an error when the workflow is trying to build.

i have this error:

Run upptime/uptime-monitor@master
  with:
    command: update-template
  env:
    GH_PAT: ***
Error: The module '/home/runner/work/_actions/upptime/uptime-monitor/master/dist/lib/binding/node_libcurl.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 7[2](https://github.com/Intelecta/upptime/actions/runs/3699841653/jobs/6267943635#step:3:2). This version of Node.js requires
NODE_MODULE_VERSION 9[3](https://github.com/Intelecta/upptime/actions/runs/3699841653/jobs/6267943635#step:3:3). Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.5367 (/home/runner/work/_actions/upptime/uptime-monitor/master/node_modules/node-libcurl/lib/binding/node_libcurl.node:1:18)
    at __webpack_require__ (/webpack/bootstrap:21:1)
    at Object.9309 (/home/runner/work/_actions/upptime/uptime-monitor/master/node_modules/node-libcurl/dist/Easy.js:5:18)
    at __webpack_require__ (/webpack/bootstrap:21:1)
    at Object.[4](https://github.com/Intelecta/upptime/actions/runs/3699841653/jobs/6267943635#step:3:4)12 (/home/runner/work/_actions/upptime/uptime-monitor/master/node_modules/node-libcurl/dist/Curl.js:17:1[6](https://github.com/Intelecta/upptime/actions/runs/3699841653/jobs/6267943635#step:3:7))

How can i solve?

**Comment by zgrossbart** [comment]
I'm seeing the same error:

```
Run upptime/uptime-monitor@master
  with:
    command: update-template
  env:
    GH_PAT: ***
Error: The module '/home/runner/work/_actions/upptime/uptime-monitor/master/dist/lib/binding/node_libcurl.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 7[2](https://github.com/zgrossbart/jdd-upptime/actions/runs/3700038045/jobs/6268343714#step:3:2). This version of Node.js requires
NODE_MODULE_VERSION 9[3](https://github.com/zgrossbart/jdd-upptime/actions/runs/3700038045/jobs/6268343714#step:3:3). Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.5367 (/home/runner/work/_actions/upptime/uptime-monitor/master/node_modules/node-libcurl/lib/binding/node_libcurl.node:1:18)
    at __webpack_require__ (/webpack/bootstrap:21:1)
    at Object.9309 (/home/runner/work/_actions/upptime/uptime-monitor/master/node_modules/node-libcurl/dist/Easy.js:5:18)
    at __webpack_require__ (/webpack/bootstrap:21:1)
    at Object.[4](https://github.com/zgrossbart/jdd-upptime/actions/runs/3700038045/jobs/6268343714#step:3:4)12 (/home/runner/work/_actions/upptime/uptime-monitor/master/node_modules/node-libcurl/dist/Curl.js:17:1[6](https://github.com/zgrossbart/jdd-upptime/actions/runs/3700038045/jobs/6268343714#step:3:7))
```

**Comment by GeekCornerGH** [comment]
Same issue for me

**Comment by tjsky** [comment]
am faced with the same problem as zgrossbart

**Comment by rblaine95** [comment]
It's likely a lot of people are also having the same problem.
To prevent spam, it's probably best to just click the "Subscribe" button on the right hand side of the issue and add a 👍 reaction to the original comment.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/4052340/207862870-1ac52d0f-975c-492e-bb6c-11bfa909eb96.png">

By subscribing to the issue, you can be notified of comments/resolution without having to add a comment saying "same" or "+1", etc.
This way, the maintainers don't have to scroll through endless " 👍 ", "Same", "+1", "me too", etc. comments, and also people subscribed to the issue don't get endless emails adding little to nothing to the issue.

**Comment by zgrossbart** [comment]
It looks like the same problem is happening to the Upptime core builds.  You can see it here:

https://github.com/upptime/upptime/actions/runs/3700291195/jobs/6268574707

This error normally means that one of the dependencies of this build now requires a newer version of Node.  This is normally a small fix, but I don't see where Upptime actually configures the build action to specify the version of Node their using.  Does anyone know where that happens?

**Comment by redoper1** [comment]
I would say it's in https://github.com/upptime/uptime-monitor/tree/master/.github/workflows. There is in "build" and "node" Node 12 specified, which is after EOL. In "release" there is Node 14.

**Comment by zgrossbart** [comment]
I've made a PR with a fix:  https://github.com/upptime/uptime-monitor/pull/205

It looks like I need a committer to approve it before the actions run and I can verify that it fixed the issue.

**Comment by zgrossbart** [comment]
Thank you for merging my PR @AnandChowdhary.  What are the next steps?  Do you need to build a release?  How can I pull this fix into [my project](https://github.com/zgrossbart/jdd-upptime/actions/runs/3707170219/jobs/6283262722)?

**Comment by redoper1** [comment]
@zgrossbart the build of the new version after merge failed, as the runner was trying to build it on Ubuntu 18.04, which is not supported by Node 18 (https://github.com/nodejs/node/issues/42351#issuecomment-1068424442).

**Comment by zgrossbart** [comment]
@redoper1, thank you for letting me know.  I thought that was part of the PR check.  Why is the runner using such an old version of Ubuntu?

**Comment by redoper1** [comment]
@zgrossbart I don't know, but it appears, that @AnandChowdhary didn't know about this issue as he tried to fix it somehow in meantime, but he wasn't successful.

**Comment by AnandChowdhary** [comment]
I'm currently working on this and investigating, will keep you posted!

**Comment by kimmy214** [comment]
same issue.

**Comment by AnandChowdhary** [comment]
This should now be fixed. You don't have to do anything to fix it in your repository, when Update Template CI runs again (within 24 hours), it should automatically use the most recent version. If you want to ensure this fix, you can also manually run Update Template CI and see it green.

**Comment by mbootsman** [comment]
Can confirm a manual run of Update Template CI works again. Thanks @AnandChowdhary and @zgrossbart!
