### ISSUE TITLE
Cannot install any node_modules on self-hosted Linux ARM64 runner

### ISSUE THREAD

**Issue by e-caste** [upptime/upptime#750]
**Describe the bug**
The error when running the "Setup Upptime" action:
```
Run upptime/uptime-monitor@v1.29.0
  with:
    command: update-template
  env:
    GH_PAT: ***
Error: /home/XXX/actions-runner/_work/_actions/upptime/uptime-monitor/v1.29.0/dist/lib/binding/node_libcurl.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.5367 (/home/ubuntu/actions-runner/_work/_actions/upptime/uptime-monitor/v1.29.0/node_modules/node-libcurl/lib/binding/node_libcurl.node:1:18)
    at __webpack_require__ (/webpack/bootstrap:21:1)
    at Object.9309 (/home/ubuntu/actions-runner/_work/_actions/upptime/uptime-monitor/v1.29.0/node_modules/node-libcurl/dist/Easy.js:5:18)
    at __webpack_require__ (/webpack/bootstrap:21:1)
    at Object.412 (/home/ubuntu/actions-runner/_work/_actions/upptime/uptime-monitor/v1.29.0/node_modules/node-libcurl/dist/Curl.js:17:16)
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Update template
```
After a bit of investigation, it turns out that node-libcurl's installation is what blocks the `npm ci/i` step with a network error, which results in the `node_modules` directory being completely absent.  
My suggestion is to resort to `npm ci/i --build-from-source` if `npm ci/i` fails.

**To Reproduce**
1. Add a self-hosted Linux ARM64 runner to the upptime repo (Ubuntu 22.04 in my case)
2. Let upptime run its actions on it
4. See the error above

**Expected behavior**
The upptime actions should run independently of the runner's architecture.

**Comment by AnandChowdhary** [comment]
Hmm, this is indeed strange.

> My suggestion is to resort to npm ci/i --build-from-source if npm ci/i fails.

Do you know how we can find out whether it failed and then run the build from source? I'm not sure if there's a "proper" API or whether we should just listen to the terminal output, but I'm happy to accept a PR!
