### ISSUE TITLE
Read-write Permission of Issues is required for the Personal Access Token

### ISSUE THREAD

**Issue by HEIGE-PCloud** [upptime/upptime#797]
**Describe the bug**
The current [documentation](https://upptime.js.org/docs/get-started#add-repository-secrets) says "In the "Permissions" > "Repository permissions" section enable read-write access to Actions, Contents, and Workflows", however, endpoint [`/repos/{owner}/{repo}/issues/{issue_number}/lock`](https://docs.github.com/en/rest/issues#lock-an-issue) is used to lock and unlock issues, which requires the [Issues permission](https://docs.github.com/en/rest/overview/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#issues) of the PAT.

The documentation needs to be reviewed and updated to reflect all permissions required.

**To Reproduce**
https://github.com/HEIGE-PCloud/doc-uptime/actions/runs/5237438276/jobs/9455617037 
```
ERROR RequestError [HttpError]: Resource not accessible by personal access token
    at /home/runner/work/_actions/upptime/uptime-monitor/v1.29.0/node_modules/@octokit/request/dist-node/index.js:68:1
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.update (/home/runner/work/_actions/upptime/uptime-monitor/v1.29.0/dist/update.js:362:1) {
  status: 403,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Sun, 11 Jun 2023 20:47:37 GMT',
    'github-authentication-token-expiration': '2024-06-10 00:00:00 +0100',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-api-version-selected': '2022-11-28',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '6304:58B4:7E1B42B:81F0E2A:648632E9',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4994',
    'x-ratelimit-reset': '1686519735',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '6',
    'x-xss-protection': '0'
  },
  request: {
    method: 'DELETE',
    url: 'https://api.github.com/repos/HEIGE-PCloud/doc-uptime/issues/2/lock',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'upptime octokit-rest.js/18.5.2 octokit-core.js/3.4.0 Node.js/12.22.7 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-length': 0
    },
    request: { hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest/reference/issues#unlock-an-issue'
}
```

**Comment by AnandChowdhary** [comment]
Thank you, you're right! Would you like to make a PR in upptime/upptime.js.org/

**Comment by HEIGE-PCloud** [comment]
> Thank you, you're right! Would you like to make a PR in upptime/upptime.js.org?

Thanks, I have submitted a fix at https://github.com/upptime/upptime.js.org/pull/47
