### ISSUE TITLE
error: failed to push some refs to 'https://'

### ISSUE THREAD

**Issue by TomlDev** [upptime/upptime#90]
I just initialized a new repo step by step as you describe it on your "Getting started" page but I get the following error after configuring:

```
#################################################
Changing directory to 'BUILD_DIR' site/status-page/__sapper__/export/ ...
#################################################
Now deploying to GitHub Pages...
Initialized empty Git repository in /github/workspace/site/status-page/__sapper__/export/.git/
[master (root-commit) 88ec494] Deploy to GitHub Pages
 39 files changed, 310 insertions(+)
 create mode 100644 404.html
 create mode 100644 client/[number]-7cdb9800.css
 create mode 100644 client/[number]-e7104239.css
 create mode 100644 client/[number].caf9d810.js
 create mode 100644 client/[number].e27ddac1.js
 create mode 100644 client/client-9c935b61.css
 create mode 100644 client/client.62c09633.js
 create mode 100644 client/createOctokit-777bf8f6.css
 create mode 100644 client/createOctokit.d581d69f.js
 create mode 100644 client/error-a44b661b.css
 create mode 100644 client/error.d7e1380d.js
 create mode 100644 client/index-87d8f7e9.css
 create mode 100644 client/index.2e47f3a3.js
 create mode 100644 client/inject_styles.5607aec6.js
 create mode 100644 client/legacy/[number]-7cdb9800.css
 create mode 100644 client/legacy/[number]-e7104239.css
 create mode 100644 client/legacy/[number].1cb27cfd.js
 create mode 100644 client/legacy/[number].b5c7560e.js
 create mode 100644 client/legacy/client-9c935b61.css
 create mode 100644 client/legacy/client.47447cf6.js
 create mode 100644 client/legacy/createOctokit-777bf8f6.css
 create mode 100644 client/legacy/createOctokit.0ef5b617.js
 create mode 100644 client/legacy/error-a44b661b.css
 create mode 100644 client/legacy/error.a8913989.js
 create mode 100644 client/legacy/index-87d8f7e9.css
 create mode 100644 client/legacy/index.794c9a83.js
 create mode 100644 client/legacy/inject_styles.fe622066.js
 create mode 100644 client/legacy/rate-limit-exceeded-e1b7a1b3.css
 create mode 100644 client/legacy/rate-limit-exceeded.33101f17.js
 create mode 100644 client/rate-limit-exceeded-e1b7a1b3.css
 create mode 100644 client/rate-limit-exceeded.db390e5b.js
 create mode 100644 client/shimport@2.0.4.js
 create mode 100644 global.css
 create mode 100644 index.html
 create mode 100644 logo-192.png
 create mode 100644 logo-512.png
 create mode 100644 manifest.json
 create mode 100644 service-worker-index.html
 create mode 100644 service-worker.js
error: src refspec ***@github.com/TomlDev/uptime-saufwaelder.git does not match any
error: failed to push some refs to 'https://'
```

**Comment by AnandChowdhary** [comment]
Can you check this, please? https://github.com/upptime/upptime/issues/61

I'm not sure exactly what to do to fix this, but it's on my radar! 💪

**Comment by TomlDev** [comment]
I tried the suggestions of https://github.com/upptime/upptime/issues/61#issuecomment-730054818
But removing the file CNAME didnt change something. And removing all files from that branch didnt change either, now the branch is empty

I just saw that I have more errors:
```
Run stefanzweifel/git-auto-commit-action@v4.5.1
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.5.1/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_BRANCH value: 
M	.github/workflows/graphs.yml
M	.github/workflows/response-time.yml
M	.github/workflows/setup.yml
M	.github/workflows/site.yml
M	.github/workflows/summary.yml
M	.github/workflows/uptime.yml
D	.templaterc.json
D	README.pt-br.md
Your branch is up to date with 'origin/master'.
INPUT_FILE_PATTERN: .
INPUT_COMMIT_OPTIONS: 
[master f793974] :arrow_up: Update @upptime to latest
 10 files changed, 82 insertions(+), 102 deletions(-)
 create mode 100644 .github/workflows/dependencies.yml
 create mode 100644 .github/workflows/updates.yml
 delete mode 100644 .templaterc.json
 delete mode 100644 README.pt-br.md
INPUT_TAGGING_MESSAGE: 
 No tagging message supplied. No tag will be added.
INPUT_PUSH_OPTIONS: 
To https://github.com/TomlDev/uptime-saufwaelder
 ! [remote rejected] master -> master (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/dependencies.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/TomlDev/uptime-saufwaelder'
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.5.1/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.5.1/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by TomlDev** [comment]
> I tried the suggestions of [#61 (comment)](https://github.com/upptime/upptime/issues/61#issuecomment-730054818)
> But removing the file CNAME didnt change something. And removing all files from that branch didnt change either, now the branch is empty
> 
> I just saw that I have more errors:
> 
> ```
> Run stefanzweifel/git-auto-commit-action@v4.5.1
> Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.5.1/entrypoint.sh
> INPUT_REPOSITORY value: .
> INPUT_BRANCH value: 
> M	.github/workflows/graphs.yml
> M	.github/workflows/response-time.yml
> M	.github/workflows/setup.yml
> M	.github/workflows/site.yml
> M	.github/workflows/summary.yml
> M	.github/workflows/uptime.yml
> D	.templaterc.json
> D	README.pt-br.md
> Your branch is up to date with 'origin/master'.
> INPUT_FILE_PATTERN: .
> INPUT_COMMIT_OPTIONS: 
> [master f793974] :arrow_up: Update @upptime to latest
>  10 files changed, 82 insertions(+), 102 deletions(-)
>  create mode 100644 .github/workflows/dependencies.yml
>  create mode 100644 .github/workflows/updates.yml
>  delete mode 100644 .templaterc.json
>  delete mode 100644 README.pt-br.md
> INPUT_TAGGING_MESSAGE: 
>  No tagging message supplied. No tag will be added.
> INPUT_PUSH_OPTIONS: 
> To https://github.com/TomlDev/uptime-saufwaelder
>  ! [remote rejected] master -> master (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/dependencies.yml` without `workflow` scope)
> error: failed to push some refs to 'https://github.com/TomlDev/uptime-saufwaelder'
> Error: Invalid status code: 1
>     at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.5.1/index.js:17:19)
>     at ChildProcess.emit (events.js:210:5)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
>   code: 1
> }
> Error: Invalid status code: 1
>     at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.5.1/index.js:17:19)
>     at ChildProcess.emit (events.js:210:5)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
> ```

Solved this by giving `workflow` privileges to my PAT

**Comment by TomlDev** [comment]
More information on the initial problem:
- occurs in `Setup CI`:
  -> when trying `Update .upptimerc.yml`
- and in `Static Site CI`:
  -> when trying `Build and deploy site`

**Comment by AnandChowdhary** [comment]
I think you should try creating a new repo and try from scratch like suggested in #61 😢 I'll also try doing that and see if I can reproduce this.

**Comment by pavelloz** [comment]
Eh, it worked for 5 days, in 6th day it broke - no changes from my part.

```
error: src refspec ***@github.com/pavelloz/instances-uptimez.git does not match any
error: failed to push some refs to 'https://'
```

**Comment by juev** [comment]
The same error here https://github.com/juev/uptime/runs/1487792194?check_suite_focus=true

**Comment by gripfastistech** [comment]
I had this the first time I set up Upptime. My noob problems resolved after I nuked the repo and started anew. Here's what worked for me:

**1. Secret key copy/paste had a preceding invisible space in it.
2. I didn't immediately comment/change the cname record so it wouldn't used the master repo address, .upptimeerc.yml lines 18-23.**
3. I didn't realize I shouldn't manually editi the ReadMe.md, rather only edit the .upptimerc.yml file.
4. Trying to set a github theme in repo Settings before a successful Actions build breaks stuff for the static site generator css.

**Comment by pavelloz** [comment]
Any other ideas how to fix repo once it breaks?
Ive nuked my repos around 6 times and sooner or later it breaks... I gave on it even though i like it when it works, but so far 100% of the times.
Its impossible to debug as its black box and breaks randomly after a day, week or month... I dont want to nuke it regularly, it was supposed to be uptime tracker with historical data.

**Comment by AnandChowdhary** [comment]
> Its impossible to debug as its black box and breaks randomly after a day, week or month... I dont want to nuke it regularly, it was supposed to be uptime tracker with historical data.

I agree, it makes no sense of deleting the repo over and over again. I sadly have no idea how to go about fixing this though. 😢

**Comment by pavelloz** [comment]
Lets brainstorm this thing then :)

1. Is it always using `https://` github origin? Because I always been taught to only use ssh:// (or git://) because otherwise i have to use login/password, and when i use ssh:// it uses ssh keys in the system. Since token is used 

That does not explain why it happens after a while, but i still cringe when i see `https://` - it always been bearer of the bad news.

2. My other guess is this: repo desynchronization when we edit some files and push them manually.

Because it tries to push to origin (static page, graphs), when there are some changes that need to be pulled, it breaks, because locally git has to be up to date to push to remote (error message is weird for that case, but it would fit into the whole "random" thing)
