### ISSUE TITLE
Self hosted runner on pi 5 doesnt work

### ISSUE THREAD

**Issue by Kitki30** [upptime/upptime#925]
Run upptime/uptime-monitor@v1.36.4
Error: /home/githubactions/actions-runner/_work/_actions/upptime/uptime-monitor/v1.36.4/dist/lib/binding/node_libcurl.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.17001 (/home/githubactions/actions-runner/_work/_actions/upptime/uptime-monitor/v1.36.4/webpack:/@upptime/uptime-monitor/node_modules/node-libcurl/lib/binding/node_libcurl.node:1:1)
    at __nccwpck_require__ (/home/githubactions/actions-runner/_work/_actions/upptime/uptime-monitor/v1.36.4/webpack:/@upptime/uptime-monitor/webpack/bootstrap:21:1)
    at Object.30376 (/home/githubactions/actions-runner/_work/_actions/upptime/uptime-monitor/v1.36.4/webpack:/@upptime/uptime-monitor/node_modules/node-libcurl/dist/Easy.js:5:1)
    at __nccwpck_require__ (/home/githubactions/actions-runner/_work/_actions/upptime/uptime-monitor/v1.36.4/webpack:/@upptime/uptime-monitor/webpack/bootstrap:21:1)
    at Object.95018 (/home/githubactions/actions-runner/_work/_actions/upptime/uptime-monitor/v1.36.4/webpack:/@upptime/uptime-monitor/node_modules/node-libcurl/dist/Curl.js:17:1)

**Comment by AnandChowdhary** [comment]
This is likely because the compiled libcurl OS doesn't match the self-hosed runner's. I'm not sure what a quick fix for this would be :(

**Comment by Kitki30** [comment]
:( its using pi os lite cause it has all drivers and cooling fan doesnt always go on full speed like on ubuntu

**Comment by taco-chen** [comment]
I've also met the same issue in a AWS ec2 instance of `t4g` family as a self-host runner:

```
Error: /home/ec2-user/heartbeats-runner/_work/_actions/upptime/uptime-monitor/v1.36.4/dist/lib/binding/node_libcurl.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
    at Module.load (node:internal/modules/cjs/loader:10[7](https://github.com/sparkful/heartbeats/actions/runs/8554709296/job/23441502870#step:3:8)6:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:1[8](https://github.com/sparkful/heartbeats/actions/runs/8554709296/job/23441502870#step:3:9))
    at Object.17001 (/home/ec2-user/heartbeats-runner/_work/_actions/upptime/uptime-monitor/v1.36.4/webpack:/@upptime/uptime-monitor/node_modules/node-libcurl/lib/binding/node_libcurl.node:1:1)
```

**Comment by taco-chen** [comment]
@AnandChowdhary, the documentation indicates that the tags for the self-hosted runners are '[self-hosted, linux, ARM64]', but the t4g family should have the same tags. Could you please guide me on the specific OS requirements of the self-hosted runner?
