### ISSUE TITLE
GitHub pages: Internal server error

### ISSUE THREAD

**Issue by not7cd** [upptime/upptime#974]
**Describe the bug**

Static github website shows 
```
Internal server error
```

This error is embeded in `index.html` suggesting that the pipeline failed to build the website.
See: https://github.com/hspsh/upptime/blob/b4fc9342d593eb5627628bb57a4b95f32f2e142e/index.html

**To Reproduce**

Create fresh upptime repo from the template.

Or in case of configuration failure, error message pointing to the problem.

**Expected behavior**

Upptime website deployed to

**Screenshots**

**Additional context**

**Comment by not7cd** [comment]
Here is a log of a failed build job https://github.com/hspsh/upptime/actions/runs/9627948403/job/26555635370

**Comment by not7cd** [comment]
Looking deeper, error at Update template step is non-failing.
```
To https://github.com/hspsh/upptime
 ! [remote rejected] master -> master (refusing to allow a GitHub App to create or update workflow `.github/workflows/graphs.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/hspsh/upptime'
All done!
```

**Comment by AnandChowdhary** [comment]
Yes, it looks like you need the right permissions: https://upptime.js.org/docs/get-started#add-repository-secrets

**Comment by PowerfulRichard** [comment]
> Yes, it looks like you need the right permissions: https://upptime.js.org/docs/get-started#add-repository-secrets

same issue here, all my permissions have been given but still fail to generate site @AnandChowdhary 
![image](https://github.com/upptime/upptime/assets/36656969/ee6c7891-1dc9-48c0-a6a3-6af6f6b95919)

https://github.com/PowerfulRichard/PT-Status/actions/runs/9826179829/job/27127323109
```
> Crawling http://localhost:3000/PT-Status/
TypeError: Cannot read properties of null (reading 'replace')
    at /home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:1058:110
    at Object.$$render (/home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:264:22)
    at /home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:1113:40
    at $$render (/home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:264:22)
    at Object.render (/home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:272:26)
    at /home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:19752:82
    at convertThrownError (/home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:19507:24)
    at detectClientOnlyReferences (/home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:19526:12)
    at /home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:19752:45
    at Generator.next (<anonymous>)
TypeError: Cannot read properties of null (reading 'replace')
    at /home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:1058:110
    at Object.$$render (/home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:264:22)
    at /home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:1113:40
    at $$render (/home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:264:22)
    at Object.render (/home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:272:26)
    at /home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:19752:82
    at convertThrownError (/home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:19507:24)
    at detectClientOnlyReferences (/home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:19526:12)
    at /home/runner/work/PT-Status/PT-Status/site/__sapper__/build/server/server.js:19752:45
    at Generator.next (<anonymous>)
      32 B   (500) index.html
      32 B   (500) service-worker-index.html
```

**Comment by Andrew-Forster** [comment]
Having a similar issue, not sure why no one has jumped on this.
