### ISSUE TITLE
tcp-ping fails with IPv6-only endpoint

### ISSUE THREAD

**Issue by martymarty004** [upptime/upptime#999]
**Describe the bug**
I recently discovered this project and immediately started using it to monitor my networks.
The only issue I found is that I'm monitoring a router which has only a public IPv6 (it's behind a NAT for IPv4).
Its IP is kept up-to-date with a DDNS service offered by the router manufacturer (AVM), in this case it has only an AAAA record and the A record is empty. The port I use to monitor if the device is up is used for diagnostics, and it's not filtered (I can easily ping it with other online services)

**To Reproduce**
1. Edit `.upptimerc.yml`
2. Add an IPv6-only hostname
3. Add `ipv6: true` parameter
4. Endpoint is detected as down

**Expected behavior**
The ping should go through, there shouldn't be any filter blocking it.
Logs are not clear about the error.

**Site configuration**
```yaml
sites:
  - name: Fritz PF
    check: "tcp-ping"
    url: $FRITZ_PF
    port: 8089  # TR-069 Port, SIP and maintenance port are also pingable remotely
    ipv6: true
```
The structure of the hostname is like this: `randomalphanumerical.myfritz.net`

**Workflow logs**
```txt
🔼 Upptime @v1.38.0
GitHub-powered open-source uptime monitor and status page by Anand Chowdhary

* Source: https://github.com/upptime/upptime
* Docs and more: https://upptime.js.org
* More by Anand Chowdhary: https://anandchowdhary.com

Found ongoing maintenance events 0

Checking $HAURL
Current status home-assistant up 2024-09-04T10:40:44.440Z
Result from test 200 7.970387
Skipping commit,  status is up

Checking $BITWARDEN
Current status bitwarden up 2024-09-04T10:40:58.448Z
Got an error (on error) [Error: Timeout was reached]
Result from test 0 0
Result from test 200 0.346212
Skipping commit,  status is up

Checking $FRITZ_PET
Current status fritz-pet up 2024-09-04T12:34:47.557Z
Using tcp-ping instead of curl
Got result {
  address: 'REDACTED',     (  <- dualstack endpint, IPv4 was used   )
  port: 8089,
  attempts: 5,
  avg: 104.3316448,
  max: 105.339329,
  min: 103.215301,
  results: [
    { seq: 0, time: 105.339329 },
    { seq: 1, time: 104.068874 },
    { seq: 2, time: 104.814586 },
    { seq: 3, time: 104.220134 },
    { seq: 4, time: 103.215301 }
  ]
}
Skipping commit,  status is up

Checking $FRITZ_PF
Current status fritz-pf down 2024-09-04T12:36:05.071Z
Using tcp-ping instead of curl
ERROR Got pinging error Error: all attempts failed
    at performTestOnce (/home/runner/work/_actions/upptime/uptime-monitor/v1.38.0/webpack:/@upptime/uptime-monitor/dist/update.js:166:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at update (/home/runner/work/_actions/upptime/uptime-monitor/v1.38.0/webpack:/@upptime/uptime-monitor/dist/update.js:282:1)
Using tcp-ping instead of curl
ERROR Got pinging error Error: all attempts failed
    at performTestOnce (/home/runner/work/_actions/upptime/uptime-monitor/v1.38.0/webpack:/@upptime/uptime-monitor/dist/update.js:166:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at update (/home/runner/work/_actions/upptime/uptime-monitor/v1.38.0/webpack:/@upptime/uptime-monitor/dist/update.js:289:1)
Using tcp-ping instead of curl
ERROR Got pinging error Error: all attempts failed
    at performTestOnce (/home/runner/work/_actions/upptime/uptime-monitor/v1.38.0/webpack:/@upptime/uptime-monitor/dist/update.js:166:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at update (/home/runner/work/_actions/upptime/uptime-monitor/v1.38.0/webpack:/@upptime/uptime-monitor/dist/update.js:297:1)
Skipping commit,  status is down

Everything up-to-date
```

**Comment by AnandChowdhary** [comment]
This is indeed strange, do you have any idea why this may have happened? For example GitHub's IP addresses are unable to visit the IP? Or any other hypotheses?

**Comment by martymarty004** [comment]
I have no clues really. I can ping the router from any IPv6 enabled network just fine, not sure why GitHub's servers can't.
For my main router I simply started pinging the public IPv4, but for the other one I didn't bother requesting for one, since I don't need it really.

**Comment by AnandChowdhary** [comment]
That's annoying indeed. Can I please ask you to do me a favor to test it out if it works by creating a GitHub Actions workflow? For example, you can create a new file in any repository:

```yaml
name: Website Health Check
on:
  workflow_dispatch:
jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check website status
        run: |
          response=$(curl -sS -o /dev/null -w "%{http_code}" http://123.45.67.89)  # Replace with your IP address
          if [ $response -eq 200 ]; then
            echo "Website is up and running!"
          else
            echo "Website is down. HTTP status code: $response"
            exit 1
          fi
```

(Make sure to replace the IP address) and then you can manually run this workflow and check what `curl` says?

**Comment by martymarty004** [comment]
I tried creating the workflow you asked me to, and it seems that GitHub can't reach that IP at all. CURL doesn't even connect and exits with an error. Since it was an HTTP get, I added the port where the UI is exposed (the same address pasted into a browser returns the login page).

Here are the logs:
```txt
##[debug]Starting: Check website status
##[debug]Loading inputs
##[debug]Loading env
Run response=$(curl -sS -o /dev/null -w "%{http_code}" http://[2a07:7e83:****:****:****:****:****]:20995)  # Replace with your IP address
  response=$(curl -sS -o /dev/null -w "%{http_code}" http://[2a07:7e83:****:****:****:****:****]:20995)  # Replace with your IP address
  if [ $response -eq 200 ]; then
    echo "Website is up and running!"
  else
    echo "Website is down. HTTP status code: $response"
    exit 1
  fi
  shell: /usr/bin/bash -e {0}
##[debug]/usr/bin/bash -e /home/runner/work/_temp/44823f3f-851f-4758-9ac0-21f033d29ed0.sh
curl: (7) Couldn't connect to server
Error: Process completed with exit code 7.
##[debug]Finishing: Check website status
```

**Comment by AnandChowdhary** [comment]
Hmm that was what I was thinking. Unfortunately, I don't think there's much we can do within Upptime if GitHub is unable to reach your IP. We'll have to figure out why this happens first, for example because of firewalls or if your server is not allowing bots or something else.

**Comment by martymarty004** [comment]
Just out of curiosity, I asked my ISP to assign me a public (dynamic) IPv4 since it is a free option.
After a quick reboot of the router, the next workflow immediately detected it as UP.
When I add `ipv6: true` to the config, it stops working again, so the issue is just with IPv6 and not some random firewall / bot filter.

**Comment by ivancarlos-me** [comment]
I have same issue, for some reason upptime is unable to reach any of my servers on AWS by IPv6

**Comment by ivancarlos-me** [comment]
Looks like we will not see Upptime checking IPv6 on GitHub for a while. https://github.com/actions/runner/issues/3138#issuecomment-2381084394

**Comment by ivancarlos-me** [comment]
I tested the workaround and it works very fine

Please @AnandChowdhary implement that on `uptime.yml` and `responde-time.yml` as first step, or let us edit that (without overwriting it), or open a new action for ipv6 tests using this trick:

```
  - name: Set up WARP
    uses: fscarmen/warp-on-actions@v1.1
    with:
      stack: ipv6
```

https://github.com/ivancarlos-me/Uptime-by-GitHub/commit/79000ae582d17275d334c3cff1e0bb6a43d3063d?diff=split&w=0

Provided by: https://github.com/fscarmen/warp-on-actions
